name: performance-test

filebeat.inputs:
- type: filestream
  id: my-filestream-id
  enabled: true
  paths:
    - /tmp/flog.ndjson
  parsers:
    - ndjson:
        target: ""
        add_error_key: true
  processors:
    - timestamp:
        field: datetime
        layouts:
          - "2006-01-02T15:04:05.999999999Z07:00" # RFC3339Nano
        test:
          - "2022-10-24T17:19:04.764155065+02:00"

queue.mem:
  events: 51200 # 2 * workers * batch size
  flush.min_events: 16000

setup.template:
  name: "filebeat-performance-test-%{[agent.version]}"
  pattern: "filebeat-performance-test-%{[agent.version]}"
  settings:
    index.number_of_shards: 6
  
output.elasticsearch:
  enabled: true
  hosts: ["${ES_HOSTS:https://localhost:9200}"]
  username: "${ES_USER:elastic}"
  password: "${ES_PASS:changeme}"
  index: "filebeat-performance-test-%{[agent.version]}"
  allow_older_versions: true
  ssl.verification_mode: ${VERIFICATION_MODE:full}
  bulk_max_size: 1600
  worker: 16
  compression_level: 9

monitoring.enabled: true
monitoring.cluster_uuid: "${CLUSTER_UUID}"

